# @s = joueur en course : anneaux (generated by tools/elyrace/gen_elyrace.py)
# Balayage : origine (position du tick precedent) et position courante, puis pour chaque anneau le segment origine -> position
# doit couper son plan dans le trou (voir sweep.py ; mg.xa = nombre d'anneaux deja valides : trou de 9 x 9, un bloc d'epaisseur)
function mg:elyrace/sweep
execute if score @s mg.xa matches 0 if score #xox mg.st matches ..13049 if score #xqx mg.st matches 13050.. run function mg:elyrace/cross {p:13050,yl:23370,yh:24269,zl:2699600,zh:2700499}
execute if score @s mg.xa matches 0 if score #xox mg.st matches ..13049 if score #xqx mg.st matches 13050.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 1 if score #xox mg.st matches ..16549 if score #xqx mg.st matches 16550.. run function mg:elyrace/cross {p:16550,yl:22370,yh:23269,zl:2700000,zh:2700899}
execute if score @s mg.xa matches 1 if score #xox mg.st matches ..16549 if score #xqx mg.st matches 16550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 2 if score #xox mg.st matches ..18549 if score #xqx mg.st matches 18550.. run function mg:elyrace/cross {p:18550,yl:21870,yh:22769,zl:2699600,zh:2700499}
execute if score @s mg.xa matches 2 if score #xox mg.st matches ..18549 if score #xqx mg.st matches 18550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 3 if score #xox mg.st matches ..22049 if score #xqx mg.st matches 22050.. run function mg:elyrace/cross {p:22050,yl:21170,yh:22069,zl:2699700,zh:2700599}
execute if score @s mg.xa matches 3 if score #xox mg.st matches ..22049 if score #xqx mg.st matches 22050.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 4 if score #xox mg.st matches ..25549 if score #xqx mg.st matches 25550.. run function mg:elyrace/cross {p:25550,yl:20470,yh:21369,zl:2699400,zh:2700299}
execute if score @s mg.xa matches 4 if score #xox mg.st matches ..25549 if score #xqx mg.st matches 25550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 5 if score #xox mg.st matches ..29049 if score #xqx mg.st matches 29050.. run function mg:elyrace/cross {p:29050,yl:19870,yh:20769,zl:2699800,zh:2700699}
execute if score @s mg.xa matches 5 if score #xox mg.st matches ..29049 if score #xqx mg.st matches 29050.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 6 if score #xox mg.st matches ..33549 if score #xqx mg.st matches 33550.. run function mg:elyrace/cross {p:33550,yl:19070,yh:19969,zl:2699400,zh:2700299}
execute if score @s mg.xa matches 6 if score #xox mg.st matches ..33549 if score #xqx mg.st matches 33550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 7 if score #xox mg.st matches ..39549 if score #xqx mg.st matches 39550.. run function mg:elyrace/cross {p:39550,yl:17470,yh:18369,zl:2700100,zh:2700999}
execute if score @s mg.xa matches 7 if score #xox mg.st matches ..39549 if score #xqx mg.st matches 39550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 8 if score #xox mg.st matches ..45549 if score #xqx mg.st matches 45550.. run function mg:elyrace/cross {p:45550,yl:16170,yh:17069,zl:2699100,zh:2699999}
execute if score @s mg.xa matches 8 if score #xox mg.st matches ..45549 if score #xqx mg.st matches 45550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 9 if score #xox mg.st matches ..50549 if score #xqx mg.st matches 50550.. run function mg:elyrace/cross {p:50550,yl:15370,yh:16269,zl:2699400,zh:2700299}
execute if score @s mg.xa matches 9 if score #xox mg.st matches ..50549 if score #xqx mg.st matches 50550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 10 if score #xox mg.st matches ..56049 if score #xqx mg.st matches 56050.. run function mg:elyrace/cross {p:56050,yl:14470,yh:15369,zl:2699700,zh:2700599}
execute if score @s mg.xa matches 10 if score #xox mg.st matches ..56049 if score #xqx mg.st matches 56050.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 11 if score #xox mg.st matches ..61249 if score #xqx mg.st matches 61250.. run function mg:elyrace/cross {p:61250,yl:13570,yh:14469,zl:2700100,zh:2700999}
execute if score @s mg.xa matches 11 if score #xox mg.st matches ..61249 if score #xqx mg.st matches 61250.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 12 if score #xox mg.st matches ..65049 if score #xqx mg.st matches 65050.. run function mg:elyrace/cross {p:65050,yl:12970,yh:13869,zl:2699800,zh:2700699}
execute if score @s mg.xa matches 12 if score #xox mg.st matches ..65049 if score #xqx mg.st matches 65050.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 13 if score #xox mg.st matches ..69049 if score #xqx mg.st matches 69050.. run function mg:elyrace/cross {p:69050,yl:12070,yh:12969,zl:2699100,zh:2699999}
execute if score @s mg.xa matches 13 if score #xox mg.st matches ..69049 if score #xqx mg.st matches 69050.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 14 if score #xox mg.st matches ..73549 if score #xqx mg.st matches 73550.. run function mg:elyrace/cross {p:73550,yl:11170,yh:12069,zl:2699000,zh:2699899}
execute if score @s mg.xa matches 14 if score #xox mg.st matches ..73549 if score #xqx mg.st matches 73550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 15 if score #xox mg.st matches ..77049 if score #xqx mg.st matches 77050.. run function mg:elyrace/cross {p:77050,yl:10670,yh:11569,zl:2699800,zh:2700699}
execute if score @s mg.xa matches 15 if score #xox mg.st matches ..77049 if score #xqx mg.st matches 77050.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 16 if score #xox mg.st matches ..80549 if score #xqx mg.st matches 80550.. run function mg:elyrace/cross {p:80550,yl:10070,yh:10969,zl:2699700,zh:2700599}
execute if score @s mg.xa matches 16 if score #xox mg.st matches ..80549 if score #xqx mg.st matches 80550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 17 if score #xox mg.st matches ..85549 if score #xqx mg.st matches 85550.. run function mg:elyrace/cross {p:85550,yl:9270,yh:10169,zl:2699400,zh:2700299}
execute if score @s mg.xa matches 17 if score #xox mg.st matches ..85549 if score #xqx mg.st matches 85550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 18 if score #xox mg.st matches ..91549 if score #xqx mg.st matches 91550.. run function mg:elyrace/cross {p:91550,yl:8170,yh:9069,zl:2699800,zh:2700699}
execute if score @s mg.xa matches 18 if score #xox mg.st matches ..91549 if score #xqx mg.st matches 91550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 19 if score #xox mg.st matches ..94549 if score #xqx mg.st matches 94550.. run function mg:elyrace/cross {p:94550,yl:7670,yh:8569,zl:2699600,zh:2700499}
execute if score @s mg.xa matches 19 if score #xox mg.st matches ..94549 if score #xqx mg.st matches 94550.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 20 if score #xox mg.st matches ..97049 if score #xqx mg.st matches 97050.. run function mg:elyrace/cross {p:97050,yl:7270,yh:8169,zl:2699600,zh:2700499}
execute if score @s mg.xa matches 20 if score #xox mg.st matches ..97049 if score #xqx mg.st matches 97050.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 21 if score #xox mg.st matches ..99049 if score #xqx mg.st matches 99050.. run function mg:elyrace/cross {p:99050,yl:6770,yh:7669,zl:2699600,zh:2700499}
execute if score @s mg.xa matches 21 if score #xox mg.st matches ..99049 if score #xqx mg.st matches 99050.. if score #xhit mg.st matches 1 run function mg:elyrace/c1/pass
# Anneau rate : le joueur est passe plus de 5 blocs derriere le plan du prochain anneau sans le franchir
execute if score @s mg.xa matches 0 positioned 136 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 1 positioned 171 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 2 positioned 191 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 3 positioned 226 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 4 positioned 261 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 5 positioned 296 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 6 positioned 341 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 7 positioned 401 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 8 positioned 461 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 9 positioned 511 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 10 positioned 566 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 11 positioned 618 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 12 positioned 656 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 13 positioned 696 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 14 positioned 741 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 15 positioned 776 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 16 positioned 811 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 17 positioned 861 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 18 positioned 921 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 19 positioned 951 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 20 positioned 976 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 21 positioned 996 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
# Anneaux d'or (trou de 7 x 7) : un turbo de 3 s chacun, mg.xo ne fait qu'augmenter (pas de recuperation apres une reprise)
execute if score @s mg.xo matches ..0 if score #xox mg.st matches ..53049 if score #xqx mg.st matches 53050.. run function mg:elyrace/cross {p:53050,yl:14870,yh:15569,zl:2700600,zh:2701299}
execute if score @s mg.xo matches ..0 if score #xox mg.st matches ..53049 if score #xqx mg.st matches 53050.. if score #xhit mg.st matches 1 run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..0 if score #xox mg.st matches ..53049 if score #xqx mg.st matches 53050.. if score #xhit mg.st matches 1 run scoreboard players set @s mg.xo 1
execute if score @s mg.xo matches ..1 if score #xox mg.st matches ..88549 if score #xqx mg.st matches 88550.. run function mg:elyrace/cross {p:88550,yl:8670,yh:9369,zl:2700700,zh:2701399}
execute if score @s mg.xo matches ..1 if score #xox mg.st matches ..88549 if score #xqx mg.st matches 88550.. if score #xhit mg.st matches 1 run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..1 if score #xox mg.st matches ..88549 if score #xqx mg.st matches 88550.. if score #xhit mg.st matches 1 run scoreboard players set @s mg.xo 2
