# @s = joueur en course : anneaux (generated by tools/elyrace/gen_elyrace.py)
# Franchissement du prochain anneau (mg.xa = nombre d'anneaux deja valides) : le joueur doit etre dans le trou de 9 x 9
execute if score @s mg.xa matches 0 positioned 109 221 26996 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 1 positioned 169 211 27010 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 2 positioned 224 202 26983 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 3 positioned 279 193 27007 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 4 positioned 334 185 26990 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 5 positioned 394 176 27004 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 6 positioned 454 167 26988 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 7 positioned 504 160 26996 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 8 positioned 559 152 26996 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 9 positioned 611 144 27006 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 10 positioned 664 136 26996 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 11 positioned 714 127 26984 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 12 positioned 764 117 27006 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 13 positioned 814 109 26987 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 14 positioned 867 103 26996 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 15 positioned 914 98 27005 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 16 positioned 949 92 26991 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 17 positioned 984 86 26994 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
# Anneau rate : le joueur est passe plus de 5 blocs derriere le plan du prochain anneau sans le franchir
execute if score @s mg.xa matches 0 positioned 116 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 1 positioned 176 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 2 positioned 231 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 3 positioned 286 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 4 positioned 341 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 5 positioned 401 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 6 positioned 461 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 7 positioned 511 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 8 positioned 566 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 9 positioned 618 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 10 positioned 671 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 11 positioned 721 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 12 positioned 771 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 13 positioned 821 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 14 positioned 874 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 15 positioned 921 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 16 positioned 956 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 17 positioned 991 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
# Anneaux d'or (trou de 7 x 7) : une fusee chacun, mg.xo ne fait qu'augmenter (pas de recuperation apres une reprise)
execute if score @s mg.xo matches ..0 positioned 480 165 27002 if entity @s[dx=3,dy=6,dz=6] run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..0 positioned 480 165 27002 if entity @s[dx=3,dy=6,dz=6] run scoreboard players set @s mg.xo 1
execute if score @s mg.xo matches ..1 positioned 637 141 26993 if entity @s[dx=3,dy=6,dz=6] run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..1 positioned 637 141 26993 if entity @s[dx=3,dy=6,dz=6] run scoreboard players set @s mg.xo 2
execute if score @s mg.xo matches ..2 positioned 841 107 27000 if entity @s[dx=3,dy=6,dz=6] run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..2 positioned 841 107 27000 if entity @s[dx=3,dy=6,dz=6] run scoreboard players set @s mg.xo 3
