# @s = joueur en course : anneaux (generated by tools/elyrace/gen_elyrace.py)
# Franchissement du prochain anneau (mg.xa = nombre d'anneaux deja valides) : le joueur doit etre dans le trou de 9 x 9
execute if score @s mg.xa matches 0 positioned 129 234 26996 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 1 positioned 164 224 27002 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 2 positioned 184 220 26995 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 3 positioned 219 212 26999 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 4 positioned 254 205 26993 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 5 positioned 289 199 27000 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 6 positioned 334 190 26992 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 7 positioned 394 174 27004 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 8 positioned 454 161 26988 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 9 positioned 504 153 26995 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 10 positioned 559 144 26996 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 11 positioned 611 136 27003 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 12 positioned 649 129 26998 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 13 positioned 689 120 26990 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 14 positioned 734 111 26988 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 15 positioned 769 106 27000 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 16 positioned 804 101 26995 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 17 positioned 854 92 26994 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 18 positioned 914 81 26998 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 19 positioned 944 76 26995 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 20 positioned 969 72 26996 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
execute if score @s mg.xa matches 21 positioned 989 67 26997 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c1/pass
# Anneau rate : le joueur est passe plus de 5 blocs derriere le plan du prochain anneau sans le franchir
execute if score @s mg.xa matches 0 positioned 136 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 1 positioned 171 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 2 positioned 191 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 3 positioned 226 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 4 positioned 261 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 5 positioned 296 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 6 positioned 341 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 7 positioned 401 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 8 positioned 461 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 9 positioned 511 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 10 positioned 566 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 11 positioned 618 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 12 positioned 656 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 13 positioned 696 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 14 positioned 741 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 15 positioned 776 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 16 positioned 811 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 17 positioned 861 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 18 positioned 921 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 19 positioned 951 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 20 positioned 976 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
execute if score @s mg.xa matches 21 positioned 996 -64 26848 if entity @s[dx=2000,dy=600,dz=304] run function mg:elyrace/miss
# Anneaux d'or (trou de 7 x 7) : une fusee chacun, mg.xo ne fait qu'augmenter (pas de recuperation apres une reprise)
execute if score @s mg.xo matches ..0 positioned 354 185 26981 if entity @s[dx=3,dy=6,dz=6] run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..0 positioned 354 185 26981 if entity @s[dx=3,dy=6,dz=6] run scoreboard players set @s mg.xo 1
execute if score @s mg.xo matches ..1 positioned 575 141 26989 if entity @s[dx=3,dy=6,dz=6] run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..1 positioned 575 141 26989 if entity @s[dx=3,dy=6,dz=6] run scoreboard players set @s mg.xo 2
execute if score @s mg.xo matches ..2 positioned 887 86 27008 if entity @s[dx=3,dy=6,dz=6] run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..2 positioned 887 86 27008 if entity @s[dx=3,dy=6,dz=6] run scoreboard players set @s mg.xo 3
