"""Tables du parcours pour les fonctions du jeu : detection des anneaux (obligatoires et d'or), anneau rate,
points de reprise, places de depart. Tout ce qui depend des coordonnees du Course est ici ; la logique de jeu
(non liee au parcours) est dans game.py.
Python stdlib uniquement (compatible 3.8).
"""
import course_canyon as K
import verify as V

MISS_MARGIN = 6          # un anneau est rate quand le joueur depasse son plan de plus de 5 blocs sans l'avoir franchi
BOX_X = 3                # volume de franchissement : de x-1 a x+4 (> deplacement maximal par tick, fusee comprise)
Y_LO, Y_SPAN = -64, 600  # zone "apres l'anneau" : toutes altitudes
Z_SPAN = K.Z1 - K.Z0


def ring_lines(c):
    """Fonction `rings` (@s = joueur en course) : franchissement du prochain anneau, anneau rate, anneaux d'or."""
    out = ['# @s = joueur en course : anneaux (generated by tools/elyrace/gen_elyrace.py)',
           '# Franchissement du prochain anneau (mg.xa = nombre d\'anneaux deja valides) : le joueur doit etre dans le trou de 9 x 9']
    for n, (x, cy, cz, zone) in enumerate(c.rings, 1):
        out.append('execute if score @s mg.xa matches %d positioned %d %d %d if entity @s[dx=%d,dy=%d,dz=%d] run function mg:elyrace/pass'
                   % (n - 1, x - 1, cy - K.HOLE // 2, cz - K.HOLE // 2, BOX_X, K.HOLE - 1, K.HOLE - 1))
    out.append('# Anneau rate : le joueur est passe plus de 5 blocs derriere le plan du prochain anneau sans le franchir')
    for n, (x, cy, cz, zone) in enumerate(c.rings, 1):
        out.append('execute if score @s mg.xa matches %d positioned %d %d %d if entity @s[dx=2000,dy=%d,dz=%d] run function mg:elyrace/miss'
                   % (n - 1, x + MISS_MARGIN, Y_LO, K.Z0, Y_SPAN, Z_SPAN))
    out.append('# Anneaux d\'or (trou de 7 x 7) : une fusee chacun, mg.xo ne fait qu\'augmenter (pas de recuperation apres une reprise)')
    for k, (x, cy, cz) in enumerate(c.golds, 1):
        cond = 'execute if score @s mg.xo matches ..%d positioned %d %d %d if entity @s[dx=%d,dy=6,dz=6]' % (k - 1, x - 1, cy - 3, cz - 3, BOX_X)
        out.append(cond + ' run function mg:elyrace/gold_hit')
        out.append(cond + ' run scoreboard players set @s mg.xo %d' % k)
    return out


def pass_lines(c):
    """Fonction `pass` (@s) : anneau valide ; les anneaux qui sont des points de reprise et l'arrivee sont aiguilles ici."""
    out = ['# @s = joueur qui vient de franchir le trou du prochain anneau : un anneau de plus (les aiguillages ci-dessous lisent le nouveau total)',
           'scoreboard players add @s mg.xa 1',
           'execute at @s run playsound minecraft:block.note_block.chime master @s ~ ~ ~ 1 1.6',
           'execute at @s run particle minecraft:happy_villager ~ ~1 ~ 0.5 0.5 0.5 0.1 12']
    for n in c.cps:
        out.append('execute if score @s mg.xa matches %d run function mg:elyrace/cp_reached' % n)
    out.append('execute if score @s mg.xa matches %d.. run function mg:elyrace/finish' % len(c.rings))
    out.append('function mg:elyrace/hud')
    return out


def respawn_lines(c):
    """Fonction `respawn` (@s) : retour au dernier point de reprise, en l'air, hauteur V.R_UP au-dessus du centre de l'anneau."""
    out = ['# @s = joueur a replacer au dernier point de reprise : mur (3 coeurs), sol, eau, trop longtemps sans planer, anneau rate',
           'scoreboard players set @s mg.xh 3',
           'scoreboard players set @s mg.xg 40',
           'scoreboard players set @s mg.xk 12',
           'scoreboard players set @s mg.xl 0',
           'scoreboard players set @s mg.xn 0',
           'scoreboard players operation @s mg.xa = @s mg.xc',
           '# #tp = 1 si la teleportation a reussi : mg.deaths n\'est remis a 0 qu\'alors (un joueur mort sera replace au tick suivant)',
           'scoreboard players set #tp mg.st 0',
           'execute if score @s mg.xc matches 0 run function mg:elyrace/place_tp']
    for n in c.cps:
        x, cy, cz, zone = c.rings[n - 1]
        out.append('execute if score @s mg.xc matches %d store success score #tp mg.st run tp @s %d.5 %d %d.5 270 0' % (n, x + V.RESPAWN_X, cy + V.R_UP, cz))
    out += ['execute if score #tp mg.st matches 1 run scoreboard players set @s mg.deaths 0',
            'execute at @s run playsound minecraft:entity.enderman.teleport master @s ~ ~ ~ 1 1',
            'execute at @s run particle minecraft:portal ~ ~1 ~ 0.4 0.8 0.4 0.3 40',
            'function mg:elyrace/hud']
    return out


def place_lines(c):
    """Fonction `place_tp` (@s, mg.ri = numero de place) : place sur la plateforme de depart, face a l'est (portillon devant)."""
    out = ['# @s = joueur : le met a sa place de depart (mg.ri), face au portillon ; #tp = 1 si la teleportation a reussi (voir respawn)']
    for i, (x, z) in enumerate(c.places, 1):
        cond = 'matches %d' % i if i < len(c.places) else 'matches %d..' % i
        out.append('execute if score @s mg.ri %s store success score #tp mg.st run tp @s %d.5 %d %d.5 270 0' % (cond, x, K.MESA + 1, z))
    return out


def functions(c):
    return {'rings': ring_lines(c), 'pass': pass_lines(c), 'respawn': respawn_lines(c), 'place_tp': place_lines(c)}
