# ------------------------------------------------------------------ armes « réelles » (Zombies / Infection) : sprites 16×16, canon vers la droite
# Exécuté par gen_rp.py (exec) : utilise png, pad, wjson, item_def, PAL, A.
GPAL = dict(PAL)
GPAL.update({'m': (52, 54, 60, 255), 'M': (32, 33, 38, 255), 'a': (128, 132, 140, 255), 'A': (170, 174, 182, 255),
             'u': (122, 80, 44, 255), 'U': (88, 56, 30, 255), 'z': (80, 255, 130, 255), 'Z': (30, 170, 70, 255),
             'q': (200, 60, 50, 255), 'Q': (130, 30, 25, 255)})
GSPR = {
    'gun_pistol': ['', '', '', '', '',
                   '    MMMMMMMMMMk',
                   '   MaAAAAAAAAAMk',
                   '   MmmmmmmmmmmMk',
                   '   MMMmMMkMMMMM',
                   '    MUUM  kk',
                   '    MUUMMMk',
                   '   MUuUM',
                   '   MUuUM',
                   '   MUUM',
                   '   MMMM'],
    'gun_smg': ['', '', '',
                '      MMMMMMM',
                ' MMMMMaAAAAAAMMMk',
                ' MmmMmmmmmmmmmmmk',
                ' MmMMMMmMMmMMMMMk',
                ' MMM  MUM MaM',
                '      MUM MaM',
                '     MUuM MaM',
                '     MUuM MaM',
                '     MUM  MMM',
                '     MMM'],
    'gun_shotgun': ['', '', '', '',
                    '        MMMMMMMMk',
                    'MMMM MMMaAAAAAAAk',
                    'MuuUMMmmmmmmmmmmk',
                    'MuuuUUMMMMuuuuuMk',
                    ' MuuuUMM MUUUUUM',
                    '  MMuUM   MMMMM',
                    '    MUM',
                    '    MMM'],
    'gun_rifle': ['', '', '', '', '',
                  '         MMMMMMMk',
                  'MMM  MMMMaAAAAAAk',
                  'MuuMMmmmmmmmmmmmk',
                  'MuuuuUUMMmMMMMMM',
                  ' MMuuUUM MaM',
                  '   MMMUM MaM',
                  '      MM MMM'],
    'gun_sniper': ['', '', '',
                   '      MMMMMM',
                   '      MAzzAM',
                   '       MMMM',
                   'MMM  MMMMMMMMMMMk',
                   'MuuMMmmmmmmmmmmmk',
                   'MuuuuUUMMmMMMMMM',
                   ' MMuuUUM',
                   '   MMMUM',
                   '      MM'],
    'gun_raygun': ['', '', '', '',
                   '     QQQQQ',
                   '    QqqqqqQ  ZZ',
                   '   QqqqqqqqQZzzZ',
                   '   QAAAAAAAAzzzzZ',
                   '   QqqqqqqqQZzzZ',
                   '    QqMMqqQ  ZZ',
                   '    MUUM',
                   '   MUuUM',
                   '   MUuUM',
                   '   MUUM',
                   '   MMMM'],
}
for name, rows in GSPR.items():
    png(os.path.join(A, 'textures', 'item', name + '.png'), pad(rows), GPAL)
    wjson(os.path.join(A, 'models', 'item', name + '.json'), {
        "parent": "minecraft:item/handheld", "textures": {"layer0": f"mg:item/{name}"},
        "display": {"firstperson_righthand": {"rotation": [0, -90, 0], "translation": [1.13, 3.2, 1.13], "scale": [0.68, 0.68, 0.68]},
                    "thirdperson_righthand": {"rotation": [0, -90, 0], "translation": [0, 2, 0.5], "scale": [0.85, 0.85, 0.85]}}})
    item_def(name, f'mg:item/{name}')
