# @s = joueur en course : anneaux (generated by tools/elyrace/gen_elyrace.py)
# Franchissement du prochain anneau (mg.xa = nombre d'anneaux deja valides) : le joueur doit etre dans le trou de 9 x 9
execute if score @s mg.xa matches 0 positioned 89 258 29596 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 1 positioned 134 249 29603 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 2 positioned 179 239 29589 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 3 positioned 224 230 29601 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 4 positioned 269 221 29597 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 5 positioned 324 209 29596 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 6 positioned 374 200 29591 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 7 positioned 424 190 29601 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 8 positioned 484 179 29596 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 9 positioned 544 168 29593 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 10 positioned 594 159 29598 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 11 positioned 644 150 29594 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 12 positioned 694 141 29598 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 13 positioned 764 128 29596 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 14 positioned 854 114 29596 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 15 positioned 909 105 29596 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 16 positioned 1009 88 29596 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 17 positioned 1049 80 29596 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 18 positioned 1081 73 29599 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 19 positioned 1111 67 29598 if entity @s[dx=3,dy=8,dz=8] run function mg:elyrace/c2/pass
# Anneau rate : le joueur est passe plus de 5 blocs derriere le plan du prochain anneau sans le franchir
execute if score @s mg.xa matches 0 positioned 96 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 1 positioned 141 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 2 positioned 186 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 3 positioned 231 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 4 positioned 276 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 5 positioned 331 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 6 positioned 381 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 7 positioned 431 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 8 positioned 491 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 9 positioned 551 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 10 positioned 601 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 11 positioned 651 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 12 positioned 701 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 13 positioned 771 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 14 positioned 861 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 15 positioned 916 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 16 positioned 1016 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 17 positioned 1056 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 18 positioned 1088 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
execute if score @s mg.xa matches 19 positioned 1118 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run function mg:elyrace/miss
# Anneaux d'or (trou de 7 x 7) : une fusee chacun, mg.xo ne fait qu'augmenter (pas de recuperation apres une reprise)
execute if score @s mg.xo matches ..0 positioned 345 204 29604 if entity @s[dx=3,dy=6,dz=6] run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..0 positioned 345 204 29604 if entity @s[dx=3,dy=6,dz=6] run scoreboard players set @s mg.xo 1
execute if score @s mg.xo matches ..1 positioned 449 185 29612 if entity @s[dx=3,dy=6,dz=6] run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..1 positioned 449 185 29612 if entity @s[dx=3,dy=6,dz=6] run scoreboard players set @s mg.xo 2
execute if score @s mg.xo matches ..2 positioned 791 123 29586 if entity @s[dx=3,dy=6,dz=6] run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..2 positioned 791 123 29586 if entity @s[dx=3,dy=6,dz=6] run scoreboard players set @s mg.xo 3
