# @s = joueur en course : anneaux (generated by tools/elyrace/gen_elyrace.py)
# Balayage : origine (position du tick precedent) et position courante, puis pour chaque anneau le segment origine -> position
# doit couper son plan dans le trou (voir sweep.py ; mg.xa = nombre d'anneaux deja valides : trou de 9 x 9, un bloc d'epaisseur)
function mg:elyrace/sweep
execute if score @s mg.xa matches 0 if score #xox mg.st matches ..9049 if score #xqx mg.st matches 9050.. run function mg:elyrace/cross {p:9050,yl:25570,yh:26469,zl:2959600,zh:2960499}
execute if score @s mg.xa matches 0 if score #xox mg.st matches ..9049 if score #xqx mg.st matches 9050.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 1 if score #xox mg.st matches ..13549 if score #xqx mg.st matches 13550.. run function mg:elyrace/cross {p:13550,yl:24670,yh:25569,zl:2960200,zh:2961099}
execute if score @s mg.xa matches 1 if score #xox mg.st matches ..13549 if score #xqx mg.st matches 13550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 2 if score #xox mg.st matches ..18049 if score #xqx mg.st matches 18050.. run function mg:elyrace/cross {p:18050,yl:23870,yh:24769,zl:2959100,zh:2959999}
execute if score @s mg.xa matches 2 if score #xox mg.st matches ..18049 if score #xqx mg.st matches 18050.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 3 if score #xox mg.st matches ..22549 if score #xqx mg.st matches 22550.. run function mg:elyrace/cross {p:22550,yl:22870,yh:23769,zl:2960000,zh:2960899}
execute if score @s mg.xa matches 3 if score #xox mg.st matches ..22549 if score #xqx mg.st matches 22550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 4 if score #xox mg.st matches ..27049 if score #xqx mg.st matches 27050.. run function mg:elyrace/cross {p:27050,yl:21970,yh:22869,zl:2959700,zh:2960599}
execute if score @s mg.xa matches 4 if score #xox mg.st matches ..27049 if score #xqx mg.st matches 27050.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 5 if score #xox mg.st matches ..32549 if score #xqx mg.st matches 32550.. run function mg:elyrace/cross {p:32550,yl:20870,yh:21769,zl:2959600,zh:2960499}
execute if score @s mg.xa matches 5 if score #xox mg.st matches ..32549 if score #xqx mg.st matches 32550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 6 if score #xox mg.st matches ..37549 if score #xqx mg.st matches 37550.. run function mg:elyrace/cross {p:37550,yl:19870,yh:20769,zl:2959200,zh:2960099}
execute if score @s mg.xa matches 6 if score #xox mg.st matches ..37549 if score #xqx mg.st matches 37550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 7 if score #xox mg.st matches ..42549 if score #xqx mg.st matches 42550.. run function mg:elyrace/cross {p:42550,yl:18970,yh:19869,zl:2960000,zh:2960899}
execute if score @s mg.xa matches 7 if score #xox mg.st matches ..42549 if score #xqx mg.st matches 42550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 8 if score #xox mg.st matches ..48549 if score #xqx mg.st matches 48550.. run function mg:elyrace/cross {p:48550,yl:17870,yh:18769,zl:2959700,zh:2960599}
execute if score @s mg.xa matches 8 if score #xox mg.st matches ..48549 if score #xqx mg.st matches 48550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 9 if score #xox mg.st matches ..54549 if score #xqx mg.st matches 54550.. run function mg:elyrace/cross {p:54550,yl:16770,yh:17669,zl:2959400,zh:2960299}
execute if score @s mg.xa matches 9 if score #xox mg.st matches ..54549 if score #xqx mg.st matches 54550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 10 if score #xox mg.st matches ..59549 if score #xqx mg.st matches 59550.. run function mg:elyrace/cross {p:59550,yl:15870,yh:16769,zl:2959700,zh:2960599}
execute if score @s mg.xa matches 10 if score #xox mg.st matches ..59549 if score #xqx mg.st matches 59550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 11 if score #xox mg.st matches ..64549 if score #xqx mg.st matches 64550.. run function mg:elyrace/cross {p:64550,yl:14970,yh:15869,zl:2959500,zh:2960399}
execute if score @s mg.xa matches 11 if score #xox mg.st matches ..64549 if score #xqx mg.st matches 64550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 12 if score #xox mg.st matches ..69549 if score #xqx mg.st matches 69550.. run function mg:elyrace/cross {p:69550,yl:14070,yh:14969,zl:2959700,zh:2960599}
execute if score @s mg.xa matches 12 if score #xox mg.st matches ..69549 if score #xqx mg.st matches 69550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 13 if score #xox mg.st matches ..76549 if score #xqx mg.st matches 76550.. run function mg:elyrace/cross {p:76550,yl:12870,yh:13769,zl:2959600,zh:2960499}
execute if score @s mg.xa matches 13 if score #xox mg.st matches ..76549 if score #xqx mg.st matches 76550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 14 if score #xox mg.st matches ..85549 if score #xqx mg.st matches 85550.. run function mg:elyrace/cross {p:85550,yl:11370,yh:12269,zl:2959600,zh:2960499}
execute if score @s mg.xa matches 14 if score #xox mg.st matches ..85549 if score #xqx mg.st matches 85550.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 15 if score #xox mg.st matches ..91049 if score #xqx mg.st matches 91050.. run function mg:elyrace/cross {p:91050,yl:10470,yh:11369,zl:2959600,zh:2960499}
execute if score @s mg.xa matches 15 if score #xox mg.st matches ..91049 if score #xqx mg.st matches 91050.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 16 if score #xox mg.st matches ..101049 if score #xqx mg.st matches 101050.. run function mg:elyrace/cross {p:101050,yl:8770,yh:9669,zl:2959600,zh:2960499}
execute if score @s mg.xa matches 16 if score #xox mg.st matches ..101049 if score #xqx mg.st matches 101050.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 17 if score #xox mg.st matches ..105049 if score #xqx mg.st matches 105050.. run function mg:elyrace/cross {p:105050,yl:7970,yh:8869,zl:2959600,zh:2960499}
execute if score @s mg.xa matches 17 if score #xox mg.st matches ..105049 if score #xqx mg.st matches 105050.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 18 if score #xox mg.st matches ..108249 if score #xqx mg.st matches 108250.. run function mg:elyrace/cross {p:108250,yl:7370,yh:8269,zl:2959800,zh:2960699}
execute if score @s mg.xa matches 18 if score #xox mg.st matches ..108249 if score #xqx mg.st matches 108250.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
execute if score @s mg.xa matches 19 if score #xox mg.st matches ..111249 if score #xqx mg.st matches 111250.. run function mg:elyrace/cross {p:111250,yl:6770,yh:7669,zl:2959800,zh:2960699}
execute if score @s mg.xa matches 19 if score #xox mg.st matches ..111249 if score #xqx mg.st matches 111250.. if score #xhit mg.st matches 1 run function mg:elyrace/c2/pass
# Anneau rate : le joueur est passe plus de 5 blocs derriere le plan du prochain anneau sans le franchir ; return : apres la reprise,
# les anneaux d'or et de vent ci-dessous liraient encore l'origine du balayage d'avant la teleportation
execute if score @s mg.xa matches 0 positioned 96 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 1 positioned 141 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 2 positioned 186 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 3 positioned 231 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 4 positioned 276 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 5 positioned 331 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 6 positioned 381 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 7 positioned 431 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 8 positioned 491 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 9 positioned 551 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 10 positioned 601 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 11 positioned 651 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 12 positioned 701 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 13 positioned 771 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 14 positioned 861 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 15 positioned 916 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 16 positioned 1016 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 17 positioned 1056 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 18 positioned 1088 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
execute if score @s mg.xa matches 19 positioned 1118 -64 29440 if entity @s[dx=2000,dy=600,dz=320] run return run function mg:elyrace/why/miss
# Anneaux d'or (trou de 7 x 7) : -2 s sur le temps final chacun (gold_hit), mg.xo ne fait qu'augmenter (un or une seule fois par course, bonus garde apres une reprise)
execute if score @s mg.xo matches ..0 if score #xox mg.st matches ..80549 if score #xqx mg.st matches 80550.. run function mg:elyrace/cross {p:80550,yl:12070,yh:12769,zl:2958800,zh:2959499}
execute if score @s mg.xo matches ..0 if score #xox mg.st matches ..80549 if score #xqx mg.st matches 80550.. if score #xhit mg.st matches 1 run function mg:elyrace/gold_hit
execute if score @s mg.xo matches ..0 if score #xox mg.st matches ..80549 if score #xqx mg.st matches 80550.. if score #xhit mg.st matches 1 run scoreboard players set @s mg.xo 1
